---
- name: download ASMLib-support
  command: "wget -q -O {{ oracleasm_support_file }} --no-cookies --no-check-certificate --header 'Cookie: oraclelicense=accept-securebackup-cookie' {{ oracleasm_support_url }}"
  poll: 10

- name: install ASMLib-support
  yum: name={{ oracleasm_support_file }} state=present

- name: download ASMLib
  command: "wget -q -O {{ oracleasm_lib_file }} --no-cookies --no-check-certificate --header 'Cookie: oraclelicense=accept-securebackup-cookie' {{ oracleasm_lib_url }}"
  poll: 10

- name: install ASMLib
  yum: name={{ oracleasm_lib_file }} state=present

- name: install kmod-oracleasm
  yum: name="kmod-oracleasm" state=present

- name: set up the oracle hostnames
  lineinfile:
    dest: /etc/hosts
    state: present
    line: "127.0.0.1 {{ item }}"
  with_items:
    - "{{ oracle_hostname }}"
    - "{{ ansible_hostname }}"

- name: oracle-recommended security limits
  lineinfile:
    dest: /etc/security/limits.conf
    state: present
    line: "{{ item }}"
  with_items:
    - "grid soft nproc 2047"
    - "grid hard nproc 16384"
    - "grid soft nofile 1024"
    - "grid hard nofile 65536"
    - "grid soft stack 10240"
    - "grid hard stack 10240"

#
# create the grid user and groups
#

- name: create initial groups for the grid user
  group: name={{ item }} state=present
  with_items:
    - oinstall
    - oper
    - asmadmin
    - asmdba
    - asmoper

- name: modify oracle user
  user:
    name: "oracle"
    groups: "dba,oper,asmdba"
    append: yes

- name: create grid user
  user:
    name: "{{ grid_user }}"
    group: "oinstall"
    groups: "asmadmin,asmdba,asmoper"
    home: /home/{{ grid_user }}
    shell: /bin/bash
    password: "{{ grid_pass }}"
    append: yes

- name: modify the permission of grid installation path
  file:
    mode: 0775
    path: "{{ grid_path }}"
    state: directory
    group: "{{ oracle_group }}"
    owner: "{{ grid_user }}"

- name: set grid user environment
  lineinfile: dest=/home/{{ grid_user }}/.bashrc state=present line="{{ item }}"
  with_items:
    - "export ORACLE_BASE={{ grid_user_env.ORACLE_BASE }}"
    - "export ORACLE_HOME={{ grid_user_env.ORACLE_HOME }}"
    - "export PATH=$PATH:$ORACLE_HOME/bin"
    - "export NLS_LANG={{ grid_user_env.NLS_LANG }}"
    - "stty erase ^H"
