---

# shell environment for the oracle user
ora_user_env:
  ORACLE_BASE: "{{ oracle_path }}/oracle"
  ORACLE_SID: "{{ oracle_db_name }}"
  ORACLE_HOME: "{{ oracle_path }}/oracle/product/11.2.0/dbhome_1"
  NLS_LANG: "Japanese_Japan.UTF8"
