---
- name: install x86_64 oracle dependencies
  yum: name={{ item }} state=present
  with_items:
    - man
    - wget
    - unzip
    - unixODBC
    - unixODBC-devel
    - unixODBC-devel*x86_64
    - unixODBC-*x86_64
    - compat-libstdc++-33
    - compat-libstdc++-296
    - compat-libstdc*x86_64
    - compat-libcap*
    - compat-glibc-2*
    - elfutils-devel*x86_64
    - glibc-*
    - gcc-c++*x86_64
    - libaio
    - libaio-devel
    - libaio-devel*x86_64
    - libtool-ltdl*x86_64
    - readline
    - libcap*x86_64
    - libattr*x86_64
    - sysstat
  # - pdksh # skip this because it's bad and we're getting ksh already
    - ksh
    - binutils
    - make
    - smartmontools
    - xauth
    - elfutils-libelf-devel

- name: selinux dependencies
  yum: name={{ item }} state=present
  with_items:
    - libselinux-python

- name: oracle-recommended sysctl
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    ignoreerrors: yes # Ignore errors about unknown keys
  with_items:
    - { name: "kernel.shmall", value: "2097152" }
    - { name: "kernel.shmmax", value: "1050470400" }
    - { name: "kernel.shmmni", value: "4096" }
    - { name: "kernel.sem", value: "250 32000 100 128" }
    - { name: "fs.file-max", value: "6815744" }
    - { name: "fs.aio-max-nr", value: "1048576" }
    - { name: "net.ipv4.ip_local_port_range", value: "9000 65500" }
    - { name: "net.core.rmem_default", value: "262144" }
    - { name: "net.core.rmem_max", value: "4194304" }
    - { name: "net.core.wmem_default", value: "262144" }
    - { name: "net.core.wmem_max", value: "1048576" }

- name: save sysctl config
  command: sysctl -p
  ignore_errors: yes # because apparently the default centos config is invalid!

# it's in the oracle recommendations. i don't even know.
- name: oracle-recommended PAM config
  lineinfile:
    dest: /etc/pam.d/login
    state: present
    line: "session required pam_limits.so"

- name: oracle-recommended security limits
  lineinfile:
    dest: /etc/security/limits.conf
    state: present
    line: "{{ item }}"
  with_items:
    - "oracle soft nproc 2047"
    - "oracle hard nproc 16384"
    - "oracle soft nofile 1024"
    - "oracle hard nofile 65536"
    - "oracle soft stack 10240"
    - "oracle hard stack 10240"

- name: disable setenforce # because oracle says so, that's why
  command: /usr/sbin/setenforce 0
  ignore_errors: yes # when SELinux disabled, an error occurred

- name: oracle-recommended selinux
  selinux: policy=targeted state=disabled

- name: stop iptables
  service: name=iptables state=stopped

#
# create the oracle user and groups
#

- name: create initial groups for the oracle user
  group: name={{ item }} state=present
  with_items:
    - "{{ oracle_group }}"
    - "{{ oracle_dba_group }}"

- name: create oracle user
  user:
    name: "{{ oracle_user }}"
    group: "{{ oracle_group }}"
    groups: "{{ oracle_dba_group }}"
    home: /home/{{ oracle_user }}
    shell: /bin/bash
    password: "{{ oracle_pass }}"
    append: yes

- name: create the oracle installation path
  file:
    mode: 0755
    path: "{{ oracle_path }}"
    state: directory
    group: "{{ oracle_group }}"
    owner: "{{ oracle_user }}"

- name: set oracle user environment
  lineinfile: dest=/home/{{ oracle_user }}/.bashrc state=present line="{{ item }}"
  with_items:
    - "export ORACLE_BASE={{ ora_user_env.ORACLE_BASE }}"
    - "export ORACLE_SID={{ ora_user_env.ORACLE_SID }}"
    - "export ORACLE_HOME={{ ora_user_env.ORACLE_HOME }}"
    - "export PATH=$PATH:$ORACLE_HOME/bin"
    - "export NLS_LANG={{ ora_user_env.NLS_LANG }}"
    - "stty erase ^H"

