---
- name: clean yum cache
  command: yum clean all
  args:
    warn: no

- name: verify rpm
  command: rpm -Va
  ignore_errors: yes

- name: install x86_64 oracle dependencies
  yum: name={{ item }} state=present
  with_items:
    - binutils
    - compat-libcap1
    - compat-libstdc++-33*x86_64
    - compat-libstdc++-33
    - gcc
    - gcc-c++
    - glibc
    - glibc*x86_64
    - glibc-devel
    - glibc-devel*x86_64
#    - ksh
    - libgcc
    - libgcc*x86_64
    - libstdc++
    - libstdc++*x86_64
    - libstdc++-devel
    - libstdc++-devel*x86_64
    - libaio
    - libaio*x86_64
    - libaio-devel
    - libaio-devel*x86_64
    - libXext
    - libXext*x86_64
    - libXtst
    - libXtst*x86_64
    - libX11
    - libX11*x86_64
    - libXau
    - libXau*x86_64
    - libxcb
    - libxcb*x86_64
    - libXi
    - libXi*x86_64
    - make-3.81
    - sysstat-9.0.4

- name: selinux dependencies
  yum: name={{ item }} state=present
  with_items:
    - libselinux-python

- name: set up the oracle hostnames
  lineinfile:
    dest: /etc/hosts
    state: present
    line: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }} {{ inventory_hostname }}"

- name: oracle-recommended sysctl
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    ignoreerrors: yes # Ignore errors about unknown keys
  with_items:
    - { name: "kernel.shmall", value: "1073741824" }
    - { name: "kernel.shmmax", value: "4398046511104" }
    - { name: "kernel.shmmni", value: "4096" }
    - { name: "kernel.sem", value: "250 32000 100 128" }
    - { name: "fs.file-max", value: "6815744" }
    - { name: "fs.aio-max-nr", value: "1048576" }
    - { name: "net.ipv4.ip_local_port_range", value: "9000 65500" }
    - { name: "net.core.rmem_default", value: "262144" }
    - { name: "net.core.rmem_max", value: "4194304" }
    - { name: "net.core.wmem_default", value: "262144" }
    - { name: "net.core.wmem_max", value: "1048576" }
    - { name: "panic_on_oops", value: "1" }

- name: save sysctl config
  command: sysctl -p
  ignore_errors: yes # because apparently the default centos config is invalid!

# it's in the oracle recommendations. i don't even know.
- name: oracle-recommended PAM config
  lineinfile:
    dest: /etc/pam.d/login
    state: present
    line: "session required pam_limits.so"

- name: oracle-recommended security limits
  lineinfile:
    dest: /etc/security/limits.conf
    state: present
    line: "{{ item }}"
  with_items:
    - "oracle soft nproc 2047"
    - "oracle hard nproc 16384"
    - "oracle soft nofile 1024"
    - "oracle hard nofile 65536"
    - "oracle soft stack 10240"
    - "oracle hard stack 32768"

#- name: disable setenforce # because oracle says so, that's why
#  command: /usr/sbin/setenforce 0
#  ignore_errors: yes # when SELinux disabled, an error occurred

#- name: oracle-recommended selinux
#  selinux: policy=targeted state=disabled

- name: stop iptables
  service: name=iptables state=stopped

#
# create the oracle user and groups
#

- name: create initial groups for the oracle user
  group: name={{ item }} state=present
  with_items:
    - "{{ oracle_group }}"
    - "{{ oracle_dba_group }}"
    - "{{ oracle_backupdba_group }}"
    - "{{ oracle_oper_group }}"
    - "{{ oracle_dgdba_group }}"
    - "{{ oracle_kmdba_group }}"

- name: create oracle user
  user:
    name: "{{ oracle_user }}"
    group: "{{ oracle_group }}"
    groups: "{{ oracle_groups }}"
    home: /home/{{ oracle_user }}
    shell: /bin/bash
    password: "{{ oracle_pass }}"
    append: yes

- name: create the oracle installation path
  file:
    mode: 0755
    path: "{{ oracle_path }}"
    state: directory
    group: "{{ oracle_group }}"
    owner: "{{ oracle_user }}"

- name: set oracle user environment
  lineinfile: dest=/home/{{ oracle_user }}/.bashrc state=present line="{{ item }}"
  with_items:
    - "export ORACLE_BASE={{ ora_user_env.ORACLE_BASE }}"
    - "export ORACLE_SID={{ ora_user_env.ORACLE_SID }}"
    - "export ORACLE_HOME={{ ora_user_env.ORACLE_HOME }}"
    - "export PATH=$PATH:$ORACLE_HOME/bin"
    - "export NLS_LANG={{ ora_user_env.NLS_LANG }}"

