---
# defaults for oracle installation

# location for temporary installation files
oracle_tmp: /tmp/oracle

#
# oracle connection settings
#

# ORACLE_BASE parent, {{ oracle_path }}/oracle
oracle_path: /u01/app

# ORACLE_SID
oracle_db_name: orcl

# ORACLE_HOME basename, {{ oracle_path }}/oracle/product/12.1.0/{{ oracle_db_home }}
oracle_db_home: oracle_db_home

#
# oracle system user
#

# oracle user username
oracle_user: oracle

# hashed password for the oracle user
# python -c 'import crypt; print crypt.crypt("oracle", "$1$salt$")'
oracle_pass: $1$salt$6hY7SFGTovD5BRJ.4zYAd1

# primary oracle group
oracle_group: oinstall

# DBA group
oracle_dba_group: dba
oracle_backupdba_group: backupdba
oracle_oper_group: oper
oracle_dgdba_group: dgdba
oracle_kmdba_group: kmdba

oracle_groups: dba,backupdba,oper,dgdba,kmdba
