---
galaxy_info:
  author: ellotheth, sugitk
  description: Oracle configuration role
  license: MIT
  min_ansible_version: 2.0
  platforms:
  - name: EL
    versions:
    - 6
  categories:
  - database
  - database:sql
dependencies: []
